name: Request

permissions:
  contents: read

on:
  pull_request_target:
  push:
    branches:
    - main
    - release/v*

concurrency:
  group: |
    ${{ github.head_ref
        || github.run_id
    }}-${{ github.workflow }}-request
  cancel-in-progress: true


jobs:
  request:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        echo "REQUESTED"
