name: WF/2

permissions:
  contents: read

on:
  workflow_run:
    workflows:
    - WF/1
    types:
    - completed

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_DEBUG: ${{ vars.CI_DEBUG }}


jobs:
  wf-2:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        echo "WF 2"
